[package]
name = "panopticon-data-flow"
version = "0.16.0"
authors = ["seu <seu@panopticon.re>"]

[dependencies]
bit-set = "0.4.0"
petgraph = "0.4.9"
env_logger = "0.3"
log = "0.3.6"
smallvec = "0.4.4"
panopticon-core = { path = "../core" }
panopticon-graph-algos = { path = "../graph-algos" }
