include ../../defaults.mk

LIBS+=-lcppunit -lpanopticum

API=$(wildcard ../include/*.hh)
TESTS=$(wildcard *.hh)

#.PHONY: clean

#all: test

#test: test.cc $(HEADERS) $(TESTS)
#	$(CXX) $(CXXARGS) $(INCLUDES) $(LIBS) -o $@ $<

#clean:
	rm -f runtests
